/*
 * masterFrame.java
 *
 * Created on May 10, 2010, 9:38 AM
 */

package ui;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.Insets;
import java.awt.SystemColor;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.Transferable;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.*;
import java.util.Vector;

import javax.swing.*;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.border.EtchedBorder;
import javax.swing.text.DefaultCaret;

import calc.BriccsWrap;
import main.Control;
import main.Run;
import main.Setup;
import nds.ensdf.MassChain;
import nds.util.Str;

import java.awt.event.ItemListener;
import java.awt.event.ItemEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 * The top-level user interface 
 * @author Jun
 */
public class MasterFrame extends javax.swing.JFrame {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	MassChain data;//all of the data in the file
    EnsdfWrap [] ensw;//wrappers for all of the endsfs in the file
    boolean isFileLoaded;
    Run run;
    
    
    public MasterFrame() {
        isFileLoaded=false;
        initComponents();
        run=new Run();
        
        pathField.setText(main.Setup.outdir);
        data=new MassChain();
        
        textArea.setFont(new Font("Courier New", Font.PLAIN, 12));

        textArea.setTransferHandler(new TransferHandler() {
            /**
			 * 
			 */
			private static final long serialVersionUID = 1L;

			public boolean canImport(TransferHandler.TransferSupport support) {
                if (!support.isDataFlavorSupported(DataFlavor.javaFileListFlavor)) {
                    return false;
                } 
                return true;
            }
     
            @SuppressWarnings("unchecked")
    		public boolean importData(TransferHandler.TransferSupport support) {
                if (!canImport(support)) {
                    return false;
                }
                 
                Transferable t = support.getTransferable();
     
                try {
                    java.util.List<File> fileList=(java.util.List<File>)t.getTransferData(DataFlavor.javaFileListFlavor);
     
                    main.Setup.filedir=fileList.get(0).getAbsolutePath();
                    main.Setup.save();
                    data.clear();
                        
                    //Very strange
                    //loadFiles((File[]) fileList.toArray()) works on Windows OS but throws cast exception in Linux
                    
                    File[] files=new File[fileList.size()];
                    fileList.toArray(files);
                    
                    loadFiles(files);
                 
                    calculate();
                    
                } catch (UnsupportedFlavorException e) {
                	e.printStackTrace();
                    return false;
                } catch (Exception e) {
                	e.printStackTrace();
                    return false;
                }
     
                return true;
            }
        });
        
        run.setMessenger(textArea);
        run.printMessage(run.title());
               
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        pathLabel = new javax.swing.JLabel();
        pathField = new javax.swing.JTextField();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        pathLabel.setText("Output path:");

        pathField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                pathFieldPropertyChange(evt);
            }
        });
        pathField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pathFieldKeyReleased(evt);
            }
        });
        
        scrollPane = new JScrollPane();
        //scrollPane.setViewportBorder(new TitledBorder(new EtchedBorder(EtchedBorder.LOWERED, null, null), "message", TitledBorder.LEADING, TitledBorder.TOP, null, new Color(0, 0, 0)));
        scrollPane.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(EtchedBorder.LOWERED),"message"));
        scrollPane.setToolTipText("display the processing status and message.");
        
        browserButton = new JButton("Browse");
        browserButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent evt) {
        		browseButtonActionPerformed(evt);
        	}
        });
        
        
        loadButton = new javax.swing.JToggleButton();
        
        loadButton.setText("Load ENSDF File(s)");
        loadButton.setToolTipText("load a single file of multiple ENSDFs or load multiple files");
        calculateButton = new javax.swing.JToggleButton();
        
        calculateButton.setText("Calculate");
        calculateButton.setToolTipText("<HTML>calculate BXLW values in input ENSDF datasets and write detailed reports.</HTML>");
        
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });
        
        iccCheckBox = new JCheckBox("ICC from BrIcc");
        iccCheckBox.setToolTipText("<HTML>If selected, use  ICC values re-calculated on-fly from the BrIcc program. <br>Otherwise, use input values given in datasets. "
        		+ "<br>By default, only CC>0.01 will be re-calculated.</HTML>");
        iccCheckBox.setSelected(!Control.isUseInputCC);
        iccCheckBox.addItemListener(new ItemListener() {
        	public void itemStateChanged(ItemEvent arg0) {
            	if(((JCheckBox)arg0.getSource()).isSelected()){
            		Control.isUseInputCC=false;
            		BriccDCCRadioButton.setEnabled(false);
            		HsiccDCCRadioButton.setEnabled(false);
            		otherDCCRadioButton.setEnabled(false);
            		textField.setEnabled(false);
            	}else{
            		Control.isUseInputCC=true;
            		BriccDCCRadioButton.setEnabled(true);
            		HsiccDCCRadioButton.setEnabled(true);
            		otherDCCRadioButton.setEnabled(true);
            		if(otherDCCRadioButton.isSelected())
            			textField.setEnabled(true);
            	}
        	}
        });
        
        iccCheckBox.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent evt) {
        		iccCheckBoxMouseClicked(evt);
        	}
        });
        
        symCheckBox = new JCheckBox("symmetrize uncertainty");
        symCheckBox.setToolTipText("symmetrize asymmetric uncertainties if applicable.");
        symCheckBox.setSelected(Control.isUseSymmetrized);
        symCheckBox.addItemListener(new ItemListener() {
        	public void itemStateChanged(ItemEvent arg0) {
            	if(((JCheckBox)arg0.getSource()).isSelected())
            		Control.isUseSymmetrized=true;
            	else
            		Control.isUseSymmetrized=false;
        	}
        });
            
        RULCheckBox = new JCheckBox("compare RUL in report");
        RULCheckBox.setToolTipText("<HTML>show RUL comparisons in report file with calculated BXLW for pure E or M.<br>"
        		+ "(it may take a while for BrIcc to calculate CC if many)</HTML>");
        RULCheckBox.setSelected(Control.isPrintRULComparison);
        RULCheckBox.addItemListener(new ItemListener() {
        	public void itemStateChanged(ItemEvent arg0) {
            	if(((JCheckBox)arg0.getSource()).isSelected())
            		Control.isPrintRULComparison=true;
            	else
            		Control.isPrintRULComparison=false;
        	}
        });
        
        limitCheckBOx = new JCheckBox("suppress BXLW limits");
        limitCheckBOx.setToolTipText("<HTML>suppress BXLW values with limits in output.</HTML>");
        limitCheckBOx.setSelected(Control.isSuppressBXLWLimit);
        limitCheckBOx.addItemListener(new ItemListener() {
        	public void itemStateChanged(ItemEvent arg0) {
            	if(((JCheckBox)arg0.getSource()).isSelected())
            		Control.isSuppressBXLWLimit=true;
            	else
            		Control.isSuppressBXLWLimit=false;
        	}
        });
        
        
        DCCLabel = new JLabel("<HTML><center> DCC<br> Theory </center></HTML>");
        DCCLabel.setToolTipText("<HTML>assumed DCC uncertainty if DCC not given <br>for using CC from datasets.</HTML>");
        
        BriccDCCRadioButton = new JRadioButton("Bricc-1.4%");
        BriccDCCRadioButton.setToolTipText("assumed uncertainty if DCC not given");
        BriccDCCRadioButton.setSelected(true);
        BriccDCCRadioButton.addItemListener(new ItemListener() {
        	public void itemStateChanged(ItemEvent e) {
            	if(((JRadioButton)e.getSource()).isSelected()){
            		Control.theoryDCC=0.014f;
            		Control.theoryDCCType="B";
            	}
        	}
        });
        
        buttonGroup.add(BriccDCCRadioButton);
        
        HsiccDCCRadioButton = new JRadioButton("Hsicc-3%");
        HsiccDCCRadioButton.setToolTipText("additional uncertainty to be added");
        BriccDCCRadioButton.addItemListener(new ItemListener() {
        	public void itemStateChanged(ItemEvent e) {
            	if(((JRadioButton)e.getSource()).isSelected()){
            		Control.theoryDCC=0.03f;
            		Control.theoryDCCType="H";
            	}
        	}
        });
        
        buttonGroup.add(HsiccDCCRadioButton);
        
        otherDCCRadioButton = new JRadioButton("other");
        otherDCCRadioButton.addItemListener(new ItemListener() {
        	public void itemStateChanged(ItemEvent e) {
            	if(((JRadioButton)e.getSource()).isSelected()){
            		textField.setEnabled(true);
            	}else{
            		textField.setEnabled(false);
            	}
        	}
        });
        
        buttonGroup.add(otherDCCRadioButton);
        
        textField = new JTextField();
        textField.addKeyListener(new KeyAdapter() {
        	public void keyReleased(KeyEvent arg0) {
        		DCCFieldKeyReleased(arg0);
        	}
        });
        textField.setColumns(10);
        textField.setEnabled(false);
        
        label = new JLabel("%");        
        
        
        this.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseClicked(MouseEvent evt) {
        		frameMouseClicked(evt);
        	}
        });
        
        JPanel panel = new JPanel();
        
        
        //////////////////////////////////////////
        // LAYOUT
        /////////////////////////////////////////
        GroupLayout groupLayout = new GroupLayout(getContentPane());
        groupLayout.setHorizontalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(panel, 0, 0, Short.MAX_VALUE))
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(12)
        					.addComponent(pathLabel, GroupLayout.PREFERRED_SIZE, 85, GroupLayout.PREFERRED_SIZE)
        					.addGap(1)
        					.addComponent(pathField, GroupLayout.PREFERRED_SIZE, 394, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(browserButton, GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(4)
        					.addComponent(scrollPane, GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)))
        			.addContainerGap())
        );
        groupLayout.setVerticalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(panel, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(pathField, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
        				.addComponent(browserButton)
        				.addComponent(pathLabel, GroupLayout.PREFERRED_SIZE, 15, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(scrollPane, GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
        			.addContainerGap())
        );
               

        GroupLayout gl_panel = new GroupLayout(panel);
        gl_panel.setHorizontalGroup(
        	gl_panel.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_panel.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(gl_panel.createParallelGroup(Alignment.LEADING)
        				.addComponent(loadButton, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE)
        				.addComponent(calculateButton, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE))
        			.addGap(30)
        			.addGroup(gl_panel.createParallelGroup(Alignment.LEADING)
        				.addGroup(gl_panel.createSequentialGroup()
        					.addGroup(gl_panel.createParallelGroup(Alignment.LEADING)
        						.addComponent(iccCheckBox, GroupLayout.PREFERRED_SIZE, 165, GroupLayout.PREFERRED_SIZE)
        						.addComponent(RULCheckBox, GroupLayout.PREFERRED_SIZE, 165, GroupLayout.PREFERRED_SIZE)
        						.addComponent(symCheckBox, GroupLayout.PREFERRED_SIZE, 179, GroupLayout.PREFERRED_SIZE))
        					.addGap(20)
        					.addComponent(DCCLabel, GroupLayout.PREFERRED_SIZE, 52, GroupLayout.PREFERRED_SIZE))
        				.addComponent(limitCheckBOx, GroupLayout.PREFERRED_SIZE, 165, GroupLayout.PREFERRED_SIZE))
        			.addGroup(gl_panel.createParallelGroup(Alignment.LEADING)
        				.addGroup(gl_panel.createSequentialGroup()
        					.addGap(1)
        					.addGroup(gl_panel.createParallelGroup(Alignment.LEADING, false)
        						.addComponent(BriccDCCRadioButton, GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
        						.addComponent(HsiccDCCRadioButton, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        				.addGroup(gl_panel.createSequentialGroup()
        					.addGap(1)
        					.addGroup(gl_panel.createSequentialGroup()
        						.addComponent(otherDCCRadioButton, GroupLayout.PREFERRED_SIZE, 64, GroupLayout.PREFERRED_SIZE)
        						.addGap(1)
        						.addComponent(textField, GroupLayout.PREFERRED_SIZE, 42, GroupLayout.PREFERRED_SIZE))
        					.addGap(1)
        					.addComponent(label, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)))
        			.addGap(13))
        );
        gl_panel.setVerticalGroup(
        	gl_panel.createParallelGroup(Alignment.TRAILING)
        		.addGroup(gl_panel.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(DCCLabel, GroupLayout.PREFERRED_SIZE, 49, GroupLayout.PREFERRED_SIZE)
        			.addGap(39))
        		.addGroup(Alignment.LEADING, gl_panel.createSequentialGroup()
        			.addGap(8)
        			.addGroup(gl_panel.createParallelGroup(Alignment.LEADING)
        				.addGroup(gl_panel.createSequentialGroup()
        					.addComponent(loadButton)
        					.addGap(22)
        					.addComponent(calculateButton)
        					.addPreferredGap(ComponentPlacement.RELATED))
        				.addGroup(gl_panel.createSequentialGroup()
        					.addGroup(gl_panel.createParallelGroup(Alignment.LEADING)
        						.addComponent(BriccDCCRadioButton)
        						.addComponent(iccCheckBox, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE))
        					.addGap(8)
        					.addGroup(gl_panel.createParallelGroup(Alignment.LEADING)
        						.addGroup(gl_panel.createSequentialGroup()
        							.addComponent(symCheckBox, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
        							.addGap(8)
        							.addComponent(RULCheckBox, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(limitCheckBOx, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE))
        						.addGroup(gl_panel.createSequentialGroup()
        							.addComponent(HsiccDCCRadioButton)
        							.addGap(8)
        							.addGroup(gl_panel.createParallelGroup(Alignment.TRAILING, false)
        								.addGroup(gl_panel.createParallelGroup(Alignment.BASELINE)
        									.addComponent(textField, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
        									.addComponent(label))
        								.addGroup(gl_panel.createSequentialGroup()
        									.addComponent(otherDCCRadioButton)
        									.addGap(5)))))))
        			.addContainerGap())
        );
        panel.setLayout(gl_panel);
        

  

        groupLayout.setHonorsVisibility(false);
        
        textArea = new JTextArea();
        //textArea.addCaretListener(new CaretListener() {
        //	public void caretUpdate(CaretEvent e) {
        //		textArea.update(textArea.getGraphics());
        //		scrollPane.update(scrollPane.getGraphics());
        //	}
       // });
        
		textArea.setMargin(new Insets(5,5,5,5));
		textArea.setEditable(false);

		DefaultCaret caret = (DefaultCaret)textArea.getCaret();
		caret.setUpdatePolicy(DefaultCaret.OUT_BOTTOM);
		//caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);

		//PrintStream printStream = new PrintStream(new CustomOutputStream(textArea));
		//System.setOut(printStream);
		
		scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
		scrollPane.add(textArea);
        scrollPane.setViewportView(textArea);

        getContentPane().setLayout(groupLayout);
        
        pack();
		textArea.setVisible(true);
        scrollPane.setVisible(true);
    }// </editor-fold>//GEN-END:initComponents
    

	private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        
        isFileLoaded=false;
         try{
             run.clear();            
             run.printMessage(run.title());
             
             //JFileChooser fc=new JFileChooser();
             JFileChooser fc;
             try {
                 fc = new JFileChooser(".");
              }catch (Exception e) {
                 fc = new JFileChooser(".", new RestrictedFileSystemView());
              }
             
             
             if(main.Setup.filedir!=null)
            	 fc.setCurrentDirectory(new File(main.Setup.filedir));
             
             fc.setMultiSelectionEnabled(true);
             
             run.infileNamesV().clear();
             
             int ret=fc.showOpenDialog(this);
             if(ret==JFileChooser.APPROVE_OPTION){
                 main.Setup.filedir=fc.getCurrentDirectory().toString();
                 main.Setup.save();
                 data.clear();
                 
                 File[] files=fc.getSelectedFiles();
                 //dataFile=fc.getSelectedFile();
                 
                 loadFiles(files);
             }       
         }catch(Exception e){
             e.printStackTrace();
             JOptionPane.showMessageDialog(this,e);         
         }

    }//GEN-LAST:event_loadButtonActionPerformed
        


	private void loadFiles(File[] files) throws IOException{

        if(files.length==1){
       	 File dataFile=files[0];
       	 String filePath=dataFile.getAbsolutePath();
       	 run.printMessage("Loading file: "+filePath);
       	 data.load(dataFile);
       	 
       	 run.infileNamesV().add(filePath);
       	 
        }else if(files.length>1){
       	 Vector<String> lines=new Vector<String>();
       	 
       	 run.printMessage("Loading files:");
       	 for(int i=0;i<files.length;i++){
       		 String filePath=files[i].getAbsolutePath();
       		 run.printMessage("    "+filePath);
       		 lines.addAll(Str.readFile(files[i]));
       		 if(!lines.lastElement().trim().isEmpty())
       			 lines.addElement("    \n");
       		 
       		 run.infileNamesV().add(filePath);
       		 
       		 //System.out.println("In MasterFrame line 362: lastline new line="+lines.lastElement().trim().indexOf("\n")+"  *"+lines.lastElement()+"*");
       	 }
       	 data.load(lines);
        }
   
                                        
        run.printMessage("Done loading");
           
        int n=data.nENSDF();

        ensw=new EnsdfWrap[n];
        for(int i=0;i<n;i++){
            ensdf.ENSDF en=data.getENSDF(i);
            ensw[i]=new EnsdfWrap(en);
        }
         
        isFileLoaded=true;
	}
	
    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableButtonActionPerformed
    	calculate();
    }//GEN-LAST:event_tableButtonActionPerformed

    private void calculate(){
        if(!isFileLoaded){
            JOptionPane.showMessageDialog(this,"You haven't loaded any ENSDF files!");
            return;
        }
        if(otherDCCRadioButton.isSelected()&&textField.getText().isEmpty()){
        	JOptionPane.showMessageDialog(this,"You haven't typed a percentage value for tehory DCC!");
        	return;
        }
        
        //check if output path exists
        File f=new File(Setup.outdir);
        if(f==null || !f.exists()){
        	String msg="The output path does not exist!\nPlease choose a new one.";
            JOptionPane.showMessageDialog(this,msg);
            return;
        }
        String outfilename="ruler.out";
        
        try{
    		
        	run.calculateAndWriteBXLW(data,outfilename);
        	Control.isNewOutpath=false;
        	
        	//Control.isUseInputCC could be changed in calculation
        	iccCheckBox.setSelected(!Control.isUseInputCC);
        	
        }catch(Exception e){
        	e.printStackTrace();
            JOptionPane.showMessageDialog(this, e);
        }
    }
    
    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {

        try{
            
            //JFileChooser fc=new JFileChooser();
            JFileChooser fc;
            try {
                fc = new JFileChooser(".");            
             }catch (Exception e) {
                fc = new JFileChooser(".", new RestrictedFileSystemView());
             }

            fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            fc.setApproveButtonText("Select");
            fc.setApproveButtonToolTipText("Select this directory");
            
            if(Setup.outdir!=null)
                fc.setCurrentDirectory(new File(Setup.outdir));
            
            int ret=fc.showOpenDialog(this);
            if(ret==JFileChooser.APPROVE_OPTION){
                //Setup.outdir=fc.getSelectedFile().toString();
            	
            	File file = fc.getSelectedFile();
            	Setup.outdir=file.getAbsolutePath();                
            	Setup.save();
                    
            	if(Setup.outdir.equals(pathField.getText()))
            		Control.isNewOutpath=false;
            	else
                	Control.isNewOutpath=true;
            
                pathField.setText(Setup.outdir);
            }
            
           
        }catch(Exception e){
            //e.printStackTrace();
           	String message="Error when selecting output path!";
           	JOptionPane.showMessageDialog(this,message);
           	run.printMessage(message);           	                         
        }

   }

    private void pathFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_pathFieldPropertyChange
        
    }//GEN-LAST:event_pathFieldPropertyChange

    private void pathFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pathFieldKeyReleased
        //specifies the path that output will be created in
        
    	if(pathField.getText().isEmpty()){
    		JOptionPane.showMessageDialog(this, "Error: empty output path!");
    		return;
    	}
    	
    	Control.isNewOutpath=true;
    	if(main.Setup.outdir.equals(pathField.getText()))
    		Control.isNewOutpath=false;
    	
    	main.Setup.outdir=pathField.getText();
        main.Setup.save();
        
        
    }//GEN-LAST:event_pathFieldKeyReleased
    
    private void DCCFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pathFieldKeyReleased
    	try{
    		Control.theoryDCC=Float.parseFloat(textField.getText())/100.0f;
    		Control.theoryDCCType="O";
    	}catch(NumberFormatException e){
    		JOptionPane.showMessageDialog(this, "Error: wrong input for DCC! Please re-type a percentage integer.");
    	}
    }


	private void frameMouseClicked(java.awt.event.MouseEvent e) {
		 if(e.getButton()==3){//right clicked
		 popupMenu=new JPopupMenu();
		 //popupMenu.setBorder(new BevelBorder(BevelBorder.RAISED));
		 //popupMenu.setBorder(BorderFactory.createEtchedBorder(EtchedBorder.LOWERED));
		 popupMenu.setBorder(BorderFactory.createEtchedBorder(EtchedBorder.RAISED, SystemColor.windowText,UIManager.getColor("ArrowButton.background")));
         popupMenu.setForeground(SystemColor.windowText);
         popupMenu.setBackground(UIManager.getColor("ArrowButton.background"));
		 
		 JMenuItem updateBriccs=new JMenuItem("Update BrIccs in output path");
		 updateBriccs.addActionListener(new ActionListener(){
		 //item.addMouseListener(new MouseAdapter(){
			 //public void mouseClicked(MouseEvent evt){
			 public void actionPerformed(ActionEvent evt){
				 
				 if(true){//if(evt.getButton()==1){//left clicked
					 //debug
					 //System.out.println("In MasterFrame: figurefiles="+run.getLatexWriter().getFigureFiles().size());
					 //run.printMessage("\nCreating PDF file from LaTex file.");
					 try {
						 
						 if(pathField.getText().isEmpty()){						     
							 JOptionPane.showMessageDialog(popupMenu,"You haven't specify the output path.");						         
							 return;						        
						 }
						 
						 //run.printMessage("Updating BrIccs files in output path with those in the package ... ");

						 run.printMessageAsIs("Updating BrIccs files in output path with those in the package ... ");
						 
						 if(BriccsWrap.checkInternalBrIccs(Setup.outdir,"FORCE"))
							 Control.isGoodBriccs=true;
						 else
							 Control.isGoodBriccs=false;
						 
						 run.printMessageAsIs("Done!\n\n");
						 
					} catch (Exception e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
						run.printMessage("Error when updating BrIccs files in output path with those in the package.\n\n");
					}
				 }
			 }
		 });
		
		 popupMenu.add(updateBriccs); 
		 	       
		 
		 JMenuItem setUncertainties=new JMenuItem("Set assumed uncertainties");
		 setUncertainties.setToolTipText("make assumptions of percentage uncertainties for non-numerical uncertainties like \"LT\",\"AP\"");
		 setUncertainties.addActionListener(new ActionListener(){
			 public void actionPerformed(ActionEvent evt){              
				 uncertaintySettingFrameActionPerformed(evt);
			 }
		 });
		 
		 popupMenu.add(setUncertainties); 
		 
		 popupMenu.show(e.getComponent(),e.getX(), e.getY());
	 }
	}
    
	private void uncertaintySettingFrameActionPerformed(ActionEvent evt){
        uncertaintySettingFrame=new UncertaintySettingFrame();
        
        //globalSettingFrame.setLocationRelativeTo(moreSettingButton);//put the center of opening frame at the center of current frame
        uncertaintySettingFrame.setLocation(this.getX()+this.getWidth(),this.getY());
        uncertaintySettingFrame.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);          
        uncertaintySettingFrame.setVisible(true); 
	}
	
    private void iccCheckBoxMouseClicked(MouseEvent e) {
		 
    	if(((JCheckBox)e.getSource()).isSelected() && e.getButton()==3){//right clicked
    		iccPopupMenu=new JPopupMenu();
   		    //iccPopupMenu.setBorder(new BevelBorder(BevelBorder.RAISED));
   		    //iccPopupMenu.setBorder(BorderFactory.createEtchedBorder(EtchedBorder.LOWERED));
   		    iccPopupMenu.setBorder(BorderFactory.createEtchedBorder(EtchedBorder.RAISED, SystemColor.windowText,UIManager.getColor("ArrowButton.background"))); 
   		    iccPopupMenu.setForeground(SystemColor.windowText);
            iccPopupMenu.setBackground(UIManager.getColor("ArrowButton.background"));

            
            largeCCcheckBox=new JCheckBox("Only calculate large CC>"+Control.largeCCLimit){
				private static final long serialVersionUID = 1L;
				@Override public void updateUI() {
                    super.updateUI();
                    setFocusPainted(false);
                }
                @Override public Dimension getMinimumSize() {
                    Dimension d = getPreferredSize();
                    d.width = Short.MAX_VALUE;
                    return d;
                }
            };
            
            largeCCcheckBox.setToolTipText("<HTML>Only calculate large CC>"+Control.largeCCLimit+" or CC not given;<br> use input CC otherwise.</HTML>");
            largeCCcheckBox.setSelected(Control.isOnlyCalculateLargeCC);
            
            largeCCcheckBox.addItemListener(new ItemListener(){
      	    //item.addMouseListener(new MouseAdapter(){
      		//public void mouseClicked(MouseEvent evt){
      			 public void itemStateChanged(ItemEvent evt){
       				 if(((JCheckBox)evt.getSource()).isSelected())
       					 Control.isOnlyCalculateLargeCC=true;
       				 else
       					 Control.isOnlyCalculateLargeCC=false;
      			 }
      		});

            largeCCcheckBox.addMouseListener(new MouseAdapter(){
				@Override
				public void mouseExited(MouseEvent e){
					iccPopupMenu.setVisible(false);
            	}
				
				@Override
				public void mouseEntered(MouseEvent e){
					iccPopupMenu.setVisible(true);
            	}
            });
            
            iccCheckBox.addMouseListener(new MouseAdapter(){
				@Override
				public void mouseExited(MouseEvent e){
					double x=e.getX();//relative to origin (top-left) of source component
					double y=e.getY();
					double w=iccCheckBox.getWidth();//upper-left point
					double h=iccCheckBox.getHeight();
					double f1=x*(x-w);
					double f2=y*(y-h);
					
					//System.out.println(" (x,y)="+x+" "+y+" f1="+f1+" f2="+f2);
					
					if(f1>=0 || f2>=0)
						iccPopupMenu.setVisible(false);
            	}
            });
            
            
      		iccPopupMenu.add(largeCCcheckBox); 
         		
      		iccPopupMenu.show(e.getComponent(),e.getX(), e.getY());
    	}	
	}
    
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MasterFrame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables


    private javax.swing.JToggleButton loadButton;
    private javax.swing.JTextField pathField;
    private javax.swing.JLabel pathLabel;
    private javax.swing.JToggleButton calculateButton;

    private JScrollPane scrollPane;
    private JTextArea textArea;
    private JButton browserButton;
    private JCheckBox iccCheckBox;
    private JCheckBox symCheckBox;
	private JPopupMenu popupMenu;
	private JPopupMenu iccPopupMenu;
	private JLabel DCCLabel;
	private final ButtonGroup buttonGroup = new ButtonGroup();
	private JTextField textField;
	private JLabel label;
	private JRadioButton BriccDCCRadioButton;
	private JRadioButton HsiccDCCRadioButton;
	private JRadioButton otherDCCRadioButton;
	private JCheckBox RULCheckBox;
	private JCheckBox limitCheckBOx;
	private JCheckBox largeCCcheckBox;
	
	private UncertaintySettingFrame uncertaintySettingFrame;
}